# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a58454d733b04daa988937ba8ae51e540af8aef2fb6cedc853eddefbb2d149e03272424743bf008db0ad1dc1a24ae8aa7e931e3c7e446b233b2df761e2b86406

test:
  secret_key_base: 1003aafb30bf4528f2054c50fd4312df3da8c2eb7135432c3ff912c59ced3556ea996eae3268ec3bbd66d1c569aca3500ab7b87c9728b70a4bcc6890abbd2061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
